name: Bug Report
description: Found a bug? Report it here.
labels: [bug]
body:
  - type: dropdown
    id: operating_system
    attributes:
      label: Operating System
      description: Select your operating system.
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: dropdown
    id: account_type
    attributes:
      label: Account Type
      description: Select your account type, if applicable.
      options:
        - Free
        - Premium
        - Public (Included)
    validations:
      required: false

  - type: dropdown
    id: service
    attributes:
      label: Service
      description: Select the service used, if applicable.
      options:
        - Spotify
        - Apple Music
        - Tidal/Deezer
        - Soundcloud
        - YouTube
        - Crunchyroll
        - Other
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A detailed description of the bug and how to reproduce it. Including logs, screenshots, or any other necessary info will help us diagnose the problem faster. Logs can be found at "%localappdata%\Temp\onthespot\logs" on Windows or "~/.cache/onthespot/logs".
    validations:
      required: true